### ISSUE TITLE
Wenn Aufgabe erledigt, soll neue Aufgabe auf der Einstiegsseite erscheinen.

### ISSUE THREAD

**Issue by aweber10** [Eclip5eLP/todo-list#2]
*Aus Anforderung 8:*
Wenn eine auf der Einstiegsseite dargestellte Aufgabe erledigt wurde, zeigt das System eine neue unerledigte Aufgabe an.

*Idee:* zunächst bleibt die erledigte Aufgabe sichtbar. Beim nächsten Einstieg in die Anwendung erscheint sie aber nichtmehr. Eine unmissverständliche Darstellung, dass die Aufgabe erledigt ist fände ich noch besser als die farbliche Markierung.

**Comment by Eclip5eLP** [comment]
Füg ich noch ein :)
